WAD2Project10A/OnlyPics/urls.py
from django.contrib import admin
from django.urls import path, include
from OnlyPics import views

app_name = "onlypics"

urlpatterns = [
    path("", views.index, name="index"),
    path("logout", views.logout_user, name="logout"),
    path("vbucks", views.vbucks, name="vbucks"),
    path("base", views.base, name="base"),
    path("about", views.about, name='about'),
    path("home", views.index, name=''),
    path("post_for_sale", views.post_for_sale, name='post_for_sale'),
    path("add_tokens", views.add_tokens, name='add_tokens'),
    path("explore", views.explore, name='explore'),
    path("upload", views.upload, name='upload'),
    path("search", views.search, name='search'),

    path("account", views.account, name='account'),
    path("edit_account", views.edit_account, name='edit_account'),
    path("delete_account", views.delete_account, name='delete_account'),

    path("post_comment", views.post_comment, name='post_comment'),
    path("like_picture", views.like_picture, name='like_picture'),

    path("buy_picture", views.buy_picture, name='buy_picture'),
    path("privacy", views.privacy_policy, name='privacy'),
    path("tos", views.terms_and_conditions, name='tos'),

]

WAD2Project10A/WAD2Project10A/urls.py
from django.contrib import admin
from django.urls import path, include
from OnlyPics import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.redirect_to_index, name="index"),
    path('onlypics/', include("OnlyPics.urls")),
    path('microsoft/', include('microsoft_auth.urls', namespace='microsoft')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

try:
    from django.contrib.sites.models import Site
    hosted_site = Site.objects.all()[0]
    if "pythonanywhere" in hosted_site.domain:
        from WAD2Project10A import github
        urlpatterns.append(path('github_web_hook', github.update))
except:
    pass

WAD2Project10A/OnlyPics/forms.py
from django import forms
from OnlyPics.models import UserInfo
from django.contrib.auth.models import User
from OnlyPics.models import Picture, Comment

class UserInfoForm(forms.ModelForm):
    nickname = forms.CharField(
        required=True,
        widget=forms.widgets.TextInput(
            attrs={
                'placeholder':'Username',
                'class':'form-control'
            }),
        max_length = UserInfo.NICKNAME_MAX_LENGTH,
        label='Username'
    )
    tokens = forms.IntegerField(widget=forms.HiddenInput(), initial=50)

    pfp = forms.FileField(
        required=True,
        label='Profile Picture'
    )

    pfp.widget.attrs.update(
        {'class':'form-control',
         'onchange':"preview()",
         'name':'filename'})

    class Meta:
        model = UserInfo
        fields = ('nickname','pfp')

class UpdateUserInfoForm(forms.ModelForm):
    nickname = forms.CharField(
        required=True,
        widget=forms.widgets.TextInput(
            attrs={
                'placeholder': 'Username',
                'class': 'form-control'
            }),
        max_length=UserInfo.NICKNAME_MAX_LENGTH,
        label='Username'
    )

    pfp = forms.FileField(
        required=True,
        label='Profile Picture'
    )

    pfp.widget.attrs.update(
        {'class': 'form-control',
         'onchange': "preview()",
         'name': 'filename'})

    class Meta:
        model = UserInfo
        fields = ('nickname', 'pfp')

class PostForSaleForm(forms.ModelForm):
    name = forms.CharField(max_length=100)    
    price = forms.IntegerField()
    createdAt = forms.DateTimeField()
    tags = forms.CharField()
    description = forms.CharField()
    upload = forms.ImageField();

    class Meta:
        model = Picture
        fields = ('name','price','createdAt','tags','description')

class PostCommentForm(forms.ModelForm):
    text = forms.CharField(max_length = 200,
                           widget=forms.widgets.TextInput(
                               attrs={
                                   'placeholder': 'Make a comment',
                                   'class': 'input-comment',
                               }),
                           label=''
                           )

    class Meta:
        model = Comment
        fields = ('text',)

WAD2Project10A/OnlyPics/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, logout

from django.core import serializers
from django.http import JsonResponse

from OnlyPics.models import UserInfo, Picture, Category, PictureVotes, Comment
from OnlyPics.forms import UserInfoForm, UpdateUserInfoForm, PostForSaleForm, PostCommentForm

from OnlyPics.hcaptcha import CaptchaException, verify_hcaptcha_request

from datetime import datetime
import numpy as np
import io
from PIL import Image
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys
import html

INVALID_CAPTCHA_REASON = "invalidCaptcha"
INVALID_PICTURE_REASON = "invalidPicture"

def resolve_error_message(error_reason):
    if error_reason == None:
        return ""
    elif error_reason == INVALID_CAPTCHA_REASON:
        return "Invalid hCaptcha. Please try again."
    elif error_reason == INVALID_PICTURE_REASON:
        return "You have uploaded an invalid picture. Please try again."
    else:
        return "Unknown error. Please try again."

#to be used in the template
def get_comments_according_to_picture(picture):
    comments = Comment.objects.filter(picture=picture)
    return comments

def redirect_to_index(request):
    return redirect('onlypics:index')

def getMostPopularCategories():
    categories = Category.objects.all()
    dictionary = {}
    for category in categories:
        dictionary[category.name] = len(Picture.objects.filter(tags=category))

    sortedDict = dict(sorted(dictionary.items(), key=lambda x: x[1], reverse=True))
    topThreeCategories = list(sortedDict.keys())[:3]

    return topThreeCategories

def index(request):
    return HttpResponse(
            """
            Connection terminated.
            I'm sorry to interrupt you, Elizabeth. If you still even remember that name.
            But I'm afraid you've been misinformed.
            """)

# testing purposes only
def base(request):
    return render(request, 'OnlyPics/base.html')

def whoami(request):
    if not request.user.is_authenticated:
        return HttpResponse(f"You are not logged in")
    user = request.user
    try:
        user_info = UserInfo.objects.get_or_create(user=user, tokens=50)[0]
        return HttpResponse(f"You are {user_info.nickname}")
    except UserInfo.DoesNotExist:
        return HttpResponse("You are logged in but there's no profile of you")
    context_dic = {}
    context_dic['topCats'] = getMostPopularCategories()
    return render(request, 'onlypics/index.html', context=context_dic)

def explore(request):
    filter_query = request.GET.get("filter", None)
    context_dic = {}
    try:
        filter_category = Category.objects.get(name = filter_query)
        picture_list = Picture.objects.filter(tags = filter_category)
    except:
        picture_list = Picture.objects.all()
    categories = Category.objects.all()
    comments = Comment.objects.all()

    user_info = None
    if request.user.is_authenticated:
        user_info = UserInfo.objects.get(user=request.user)
        context_dic['user_info'] = user_info

    forbidden_pics = []
    for pic in picture_list:
        if user_info and not can_buy_picture(user_info, pic):
            forbidden_pics.append(pic)

    disliked_pics = []
    liked_pics = []
    if user_info:
        for pic in picture_list:
            try:
                if PictureVotes.objects.get(user = user_info, picture = pic).positive:
                    liked_pics.append(pic)
                else:
                    disliked_pics.append(pic)
            except:
                pass


    form = PostCommentForm()
    context_dic['pictures'] = picture_list
    context_dic['categories'] = categories
    context_dic['topCats'] = getMostPopularCategories()
    context_dic['comments'] = comments
    context_dic['form'] = form
    context_dic['forbidden_pics'] = forbidden_pics
    context_dic['not_logged_in'] = user_info == None
    context_dic['disliked_pics'] = disliked_pics
    context_dic['liked_pics'] = liked_pics

    return render(request, 'onlypics/explore.html', context=context_dic)

def about(request):
    context_dic = {}
    context_dic['topCats'] = getMostPopularCategories()
    return render(request, 'onlypics/about.html', context=context_dic)

# convert to jpeg and ensure file is a picture
def image_reformat(image):
    img_io = io.BytesIO()
    img = Image.open(image)
    img.save(img_io, format="PNG")
    new_pic = InMemoryUploadedFile(img_io, 'ImageField', image.name, 'JPEG', sys.getsizeof(img_io), None)
    return new_pic

@login_required
def post_for_sale(request):
    if request.method == 'POST':
        old_image_id = None
        try:
            user = UserInfo.objects.get(user=request.user)
            query = request.POST
            is_new_image = True
            try:
                picture_id = query['target']
                picture = Picture.objects.get(id = picture_id)
                is_new_image = False
                old_image_id = picture_id
            except:
                picture = Picture()
            picture.owner = user
            if query.get('forSale', None) == 'on':
                picture.price = max(int(query['price']), -1)
            else:
                picture.price = -1
            picture.tags = Category.objects.get(name=query['category'])
            picture.createdAt = query['createdAt']
            picture.name = query['name']
            if is_new_image:
                image = request.FILES['upload']
                image = image_reformat(image)
                picture.upload.save(image.name, image)
            picture.save()
            return redirect('onlypics:account')
        except Exception as e:
            redirect_uri = request.build_absolute_uri()
            if old_image_id != None:
                redirect_uri += "?error=unknown&picture=" + old_image_id
            else:
                redirect_uri += "?error=" + INVALID_PICTURE_REASON
            return redirect(redirect_uri)

    try:
        target_picture = request.GET.get("picture", None)
        target_picture = Picture.objects.get(id = target_picture)
    except:
        target_picture = None

    context_dic = {}
    context_dic["categories"] = Category.objects.all()
    context_dic['topCats'] = getMostPopularCategories()
    context_dic["error_message"] = resolve_error_message(request.GET.get("error", None))
    context_dic["target"] = target_picture
    return render(request, 'onlypics/post_for_sale.html', context_dic)

# calculate how many tokens should be gained
# in add_tokens.html
def calculate_tokens_gain(user):
    return 50

@login_required
def add_tokens(request):
    topCategories = getMostPopularCategories()
    INVALID_CAPTCHA_REASON = "invalidCaptcha"
    user = UserInfo.objects.get(user=request.user)
    if request.method == 'POST':
        try:
            verify_hcaptcha_request(request)
            user.tokens += calculate_tokens_gain(request)
            user.save()
            return redirect('onlypics:add_tokens')
        except CaptchaException:
            return redirect(reverse('onlypics:add_tokens') + "?error=" + INVALID_CAPTCHA_REASON)
        except Exception:
            return redirect(reverse('onlypics:add_tokens') + "?error=unknown")
    else:
        gain = calculate_tokens_gain(user)
        current_tokens = user.tokens
        error_message = resolve_error_message(request.GET.get("error", None))
        context_dic = {"gain":  gain, 'current_tokens': current_tokens, 'error_msg': error_message, 'topCats': topCategories}
        return render(request, 'onlypics/add_tokens.html', context_dic)

@login_required
def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect('onlypics:index')

@login_required
def upload(request):
    form = UserInfoForm()
    user = request.user
    try:
        user_info = UserInfo.objects.get(user=user)
    except UserInfo.DoesNotExist:
        if request.method == 'POST':
            form = UserInfoForm(request.POST, request.FILES)
            if form.is_valid():
                if user:
                    user_info = form.save(commit=False)
                    user_info.user = user
                    user_info.save()

                    return redirect('onlypics:index')
            else:
                print(form.errors)
    else:
        return redirect('onlypics:index')

    return render(request, 'onlypics/upload.html', {'form':form})

def search(request):
    search_term = ""
    if request.user.is_authenticated:
        categories = Category.objects.all()
        disallowed_characters = "._! ,/[]()"

        if 'search' in request.GET:
            search_term = request.GET['search']
        for character in disallowed_characters:
            search_term = search_term.replace(character, "")

        if (len(search_term) == 0):
            context_dic_empty = {}
            picture_list = Picture.objects.all()
            context_dic_empty['pictures'] = picture_list
            context_dic_empty['categories'] = categories
            return render(request, 'onlypics/explore.html', context=context_dic_empty)

        picture_list = calcDictDistance(search_term)
        context_dic = {}
        context_dic['pictures'] = picture_list
        context_dic['categories'] = categories
        return render(request, 'onlypics/explore.html', context=context_dic)
    else:
        return HttpResponse("You have already logged out.")
        redirect('onlypics:explore')

def levenshteinDistanceDP(token1, token2):
    if token1 == "":
        return len(token2)
    if token2 == "":
        return len(token1)

    target = [k for k in token1]
    source = [k for k in token2]

    distances = np.zeros((len(source), len(target)))

    distances[0] = [j for j in range(len(target))]
    distances[:,0] = [j for j in range(len(source))]

WAD2Project10A/templates/onlypics/account.html
{% extends 'onlypics/base.html' %}

{% load staticfiles %}
{% load onlypics_template_filters %}

{% block title_block %}
    Account
{% endblock %}

{% block cssFile %}
    <link rel="stylesheet" href="{% static 'css/account.css'%}" type="text/css">

<!-- Fonts access -->
    <link href='https://fonts.googleapis.com/css?family=Alegreya Sans SC' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Kalam' rel='stylesheet'>

<!-- Download icon -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

{% endblock %}

{% block body_block %}
<div class="container-fluid">
      <div class="row">
        <div class="col-3 sticky">
          <div class="sidebar-section">
              <div>
                  {% if user.is_authenticated %}
                    <img id="profile-picture" src="{{ MEDIA_URL }}{{ userInfo.pfp }}">
                    <p id="account-name">{{ userInfo.nickname }}</p>
                    <p class="account-info">Tokens: {{ userInfo.tokens }}</p>
                    <p class="account-info">Pictures owned: {{ len_pics }}</p>
                  {% else %}
                    <p>This account does not exist</p>
                  {% endif %}
              </div>
              <div>
                  <div><a class="account-option" href="{% url 'onlypics:edit_account'%}">Edit Account</a></div>
                  <div><a class="account-option" href="{% url 'onlypics:delete_account'%}">Delete Account</a></div>
                  <div><a class="account-option" href="{% url 'onlypics:post_for_sale'%}">Sell pictures</a></div>
                  <div><a class="account-option" href="{% url 'onlypics:add_tokens'%}">Get the daily amount of tokens</a></div>
              </div>
          </div>
        </div>
        <div class="col-9">
          <div class="content-section">
              <div id="page-title">
                  This is your photo library...
              </div>
              {% if pictures %}
                  {% for pic in pictures %}
              <p style="margin-top: 15px; margin-bottom: 0; font-size: 25px;">Picture name: <strong>{{pic.name}}</strong></p>
                      <div class="picture-box">
                          <img class="owned-img" src="{{ MEDIA_URL }}{{pic.upload}}">
                      </div>
                        <div id="content">
                            <p class="info-explore-picture">Likes: {{ positiveVotes|picVoteValue:pic }}</p>
                            <p class="info-explore-picture">Dislikes: {{ negativeVotes|picVoteValue:pic }}</p>
                            {% if pic.price >= 0 %}
                            <p class="info-explore-picture">Price: {{ pic.price }}</p>
                            {% endif %}
                            <a href="{% url 'onlypics:post_for_sale' %}?picture={{ pic.id }}">
                                <button style="margin-left: 10px" class="btn download-button"><i class="fa fa-pencil"></i> Edit</button>
                            </a>
                            <a href="{{ MEDIA_URL }}{{pic.upload}}" download="{{pic.name}}">
                                <button style="margin-left: 10px" class="btn download-button"><i class="fa fa-download"></i> Download</button>
                            </a>
                        </div>
                        <div id="delimiter"></div>
                  {% endfor %}
              {% else %}
                    <p>You dont own any pictures! Time to become an owner!</p>
              {% endif %}
          </div>
        </div>
      </div>
</div>
{% endblock %}

{% block javaScript %}
{% endblock %}

WAD2Project10A/templates/onlypics/base.html
<!DOCTYPE html>
{% load staticfiles%}
{% load staticfiles %}

<html lang="en">
<head lang="en">
    <meta charset="UTF-8">
    <title>OnlyPics -
        {% block title_block %}
        Base
        {% endblock %}
    {% block title_block %}
        Base
    {% endblock %}
    </title>

    <!-- this is an icon kit for the search icon && Bootstrap -->
    <script src="https://kit.fontawesome.com/a1a588f336.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'cssFiles/base.css' %}" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Bad Script' rel='stylesheet'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css'%}" type="text/css">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    {% block cssFile %}
    {% endblock %}
</head>
<body>
    <!-- This is the header -->

    <div class="navbarHeader">
        <div class="fixed-container">
            <div class="row align-items-center">
                <div class="col-md-2"><p>OnlyPics</p></div>
                <div class="col-md-6">
                    <div class="navbar">
                        <ul class="navbarBtns">
                            <li><a href="#home">Home</a></li>
                            <li><a href="#explore">Explore</a></li>
                            <li><a href="#about">About</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="#logout">Log out</a></li>
                            <li><a href="#account">Account</a></li>
                        {% else %}
                            <li><a href="#login">Log in</a></li>
                        {% endif%}
                <div class="col-md-2"><p style="margin: 15px;: 30px;"><a href="{% url 'onlypics:index' %}" id="logo">OnlyPics</a></p></div>
                <div class="col-md-6">
                    <div class="navbar">
                        <ul class="navbarBtns">
                            <li><a href="{% url 'onlypics:index'%}">Home</a></li>
                            <li><a href="{% url 'onlypics:explore'%}">Explore</a></li>
                            <li><a href="{% url 'onlypics:about'%}">About</a></li>
                        {% if user.is_authenticated%}
                            <li><a href="{% url 'onlypics:logout'%}">Log out</a></li>
                            <li><a href="{% url 'onlypics:account'%}">Account</a></li>
                            <li><a href="{% url 'onlypics:post_for_sale'%}">Sell Pictures</a></li>
                        {% else %}
                            <li><a href="/microsoft/to-auth-redirect/?next=/onlypics/upload">Log in</a></li>
                        {% endif %}
                        </ul>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="input-group rounded">
                      <input type="search" class="form-control rounded form-control-sm" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
                      <span class="input-group-text border-0" id="search-addon">
                        <i class="fas fa-search"></i>
                      </span>
                        <form method="GET" action="{% url 'onlypics:search' %}" >
                            <input type="search" name="search" class="form-control rounded form-control-sm search-bar" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
                        </form>
                        <button type="submit">
                             <span class="input-group-text border-0" id="search-addon">
                                 <i class="fas fa-search"></i>
                             </span>
                        </button>

                    </div>
                </div>
            </div>
        </div>
    </div>


    {% block body_block %}
    {% endblock %}

    <!-- This is the footer -->

    <div class="fixed-bottom">
    <div class="fixed-container">
    <footer class=" footer-gradient fixed-bottom">
    <div class=" fixed-container ">
        <!-- This will hold [Popular Categories, About Us, OnlyPics text]-->
        <div class="footer">
            <div class="row" align="center">
            <div class="col-md-4">
                <p>Popular Categories</p>
            </div>
            <div class="col-md-4">
                <p>About Us</p>
            </div>
            <div class="col-md-4">
                <p>OnlyPics</p>
                <p class="footer-title">Popular Categories</p>
            </div>
            <div class="col-md-4">
                <p class="footer-title">About Us</p>
            </div>
            <div class="col-md-4">
                <p class="footer-title">OnlyPics</p>
            </div>
        </div>

        <!-- This will hold [The categories (ordered), about us sublinks, [privacy policy, T&Cs]]-->
        <div class="row" align="center">
            <div class="col-md-4">
                {% if categories %}
                    {% for c in categories %}
                        <li class="categoryList">
                            <a href="#category">{{ category.name }}</a>
                        </li>
                    {% endfor %}
                {% else %}
                    <p>None</p>
                {% endif %}
            </div>
            <div class="col-md-4">
                <li class="aboutUsList">
                    <a href="#about">Visit our about page</a>
                </li>
                <li class="aboutUsList">
                    <a href="#faqs">FAQs</a>
                </li>
                <li class="aboutUsList">
                    <a href="#contact">Contact Us</a>
                </li>
            </div>
            <div class="col-md-4">
                <li class="OnlyPicsList">
                    <a href="#privPolicy">Privacy Policy</a>
                </li>
                <li class="OnlyPicsList">|</li>
                <li class="OnlyPicsList">
                    <a href="#tAndCs">Terms and Conditions</a>
                {% if topCats %}
                    {% for c in topCats %}
                        <li class="footerList">
                            <a href="{% url 'onlypics:explore' %}?filter={{ c }}">{{ c }}</a>
                        </li>
                    {% endfor %}
                {% else %}
                    <li class="categories">None</li>
                {% endif %}
            </div>
            <div class="col-md-4">
                <li class="footerList">
                    <a href="{% url 'onlypics:about'%}#about-us">Visit our about page</a>
                </li>
                <li class="footerList">
                    <a href="{% url 'onlypics:about'%}#faqs">FAQs</a>
                </li>
                <li class="footerList">
                    <a href="{% url 'onlypics:about'%}#contact-us">Contact Us</a>
                </li>
            </div>
            <div class="col-md-4">
                <li class="footerList">
                    <a href="{% url 'onlypics:privacy' %}">Privacy Policy</a>
                </li>
                <li class="footerList">
                    <a href="{% url 'onlypics:tos' %}">Terms and Conditions</a>
                </li>
            </div>
        </div>
        </div>
    </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>
    </footer>


    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block javascript %}
    {% endblock %}
</body>
</html>

WAD2Project10A/templates/onlypics/delete_account.html
<!doctype html>
{% load staticfiles%}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Delete account</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.0/examples/sign-in/signin.css" rel="stylesheet">
  </head>

  <body class="text-center">
    <form class="form-signin" method="POST" enctype="multipart/form-data" action="{% url 'onlypics:delete_account'%}">
      {% csrf_token %}
        <h1 id="logo">OnlyPics</h1>
        <br>
      <h2 class="h3 mb-3 font-weight-normal">Are you sure you want to delete your account?<br>
          All of your photos will be deleted and you will lose all your tokens!</h2><br/>
      <input class="btn btn-lg btn-primary btn-block" type="submit" value="Yes"/>
      <a href="{% url 'onlypics:account'%}" class="btn btn-lg btn-primary btn-block" role="button">Cancel</a>
      <p class="mt-5 mb-3 text-muted">&copy; 2021-2022</p>
    </form>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="{% static 'javascript/upload.js'%}"></script>
  </body>
</html>

WAD2Project10A/templates/onlypics/edit_account.html
<!doctype html>
{% load staticfiles%}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Edit account</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.0/examples/sign-in/signin.css" rel="stylesheet">
  </head>

  <body class="text-center">
    <form class="form-signin" method="POST" enctype="multipart/form-data" action="{% url 'onlypics:edit_account'%}">
      {% csrf_token %}
        <h1 id="logo">OnlyPics</h1>
        <br>
      <h2 class="h3 mb-3 font-weight-normal">Choose a new username and picture to update your profile!</h2>
      {{ form }}
      <img id="pic" width="150px"/>

      <input class="btn btn-lg btn-primary btn-block" type="submit"></input>

      <a href="{% url 'onlypics:account'%}" class="btn btn-lg btn-primary btn-block" role="button">Cancel</a>
      <p class="mt-5 mb-3 text-muted">&copy; 2021-2022</p>

      <a style="color: #bd2130">{{ error_message }}</a>
    </form>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="{% static 'javascript/upload.js'%}"></script>
  </body>
</html>